= Halkyon capability plugins architecture

Part of what makes https://github.com/halkyonio/operator[Halkyon] interesting is the capability system. While the capability
concept is powerful, it only makes sense if capabilities can be added to Halkyon without requiring to modify its core. The
goal of this plugin architecture is to make it as easy as possible to extend Halkyon by adding new capabilities as plugins. This
has also the added advantage of being able to decouple the releases of the operator and that of its plugins, which can evolve
separately (as long as API compatibility is maintained, of course).

== Architecture overview

The plugin architecture relies at its core on https://github.com/hashicorp/go-plugin[Hashicorp's go-plugin]. This, in turns,
means that Halkyon plugins run as separate processes of the operator, relying on RPC communication with the core. A plugin,
therefore, consists in two parts:

- a client that runs in the operator process, controlling the lifecycle of and interacting with
the second part of the plugin,
- a server running in a separate process, implementing the plugin behavior.

However, from a user's point of view, much, if not all, of that complexity is hidden. We also made a point of hiding that
complexity for plugins implementors so that it is as easy as possible to create new plugins, without having to worry about the
RPC infrastructure. Each plugin is compiled into a binary and needs to follow some conventions in order to be automatically discoverable and downloadable by the operator.

NOTE: While the use of RPC makes it technically possible to write plugins using different programming languages, we focused our
efforts (and will only document) the use case of a Go-based plugin.

=== Client

The operator is only superficially aware of plugins: it loads them from a local `plugins` directory where each file is assumed
to be a capability plugin which path is passed to the `NewPlugin` function. See <<Using plugins in Halkyon>> for more details.

This function sets the RPC plumbing, in particular, starts the plugin process, opens a client to it and registers the plugin so
that the operator knows which capabilities it provides. All this is executed when the operator starts in its `main` function.
From there, the operator is only aware of the plugin when it attempts to create a capability: based on the requested category
and type combination, the operator will look for a plugin supporting such a pair to initialize the dependents of the capability
object.
If a plugin is found, the operator proceeds transparently interacting with the plugin via the capability object.
If no plugin is found to support the category and type of the desired capability, the capability is set in error until a plugin
can be provided (at this time, after an operator restart) to support it.

Here is the `Plugin` interface that the operator interacts with, though technically, it only ever calls `GetTypes`
and `ReadyFor` directly:

[source,go]
----
// Plugin is the operator-facing interface that can be interacted with in Halkyon
type Plugin interface {
	// Name returns the name of this Plugin
	Name() string
	// GetCategory retrieves the CapabilityCategory supported by this Plugin
	GetCategory() halkyon.CapabilityCategory
	// GetTypes returns TypeInfo providing information about CapabilityTypes this Plugin supports
	GetTypes() []TypeInfo
	// ReadyFor initializes the DependentResources needed by the given Capability and readies the Plugin for requests by the host.
	// Note that the order in which the DependentResources are returned is significant and the operator will process them in the
	// specified order. This is needed because some capabilities might require some dependent resources to be present before
	// processing others.
	ReadyFor(owner *halkyon.Capability) []framework.DependentResource
	// Kill kills the RPC client and server associated with this Plugin when the host process terminates
	Kill()
}
----

The client takes care of marshalling requests to the plugin in the appropriate format and calls the associated server without
the operator being none the wiser.

NOTE: Plugin implementors must not implement this interface directly. See <<Plugin implementation>> for more details.

=== Server

Here is the server interface:

[source,go]
----
type PluginServer interface {
	Build(req PluginRequest, res *BuildResponse) error
	GetCategory(req PluginRequest, res *halkyon.CapabilityCategory) error
	GetDependentResourceTypes(req PluginRequest, res *[]schema.GroupVersionKind) error
	GetTypes(req PluginRequest, res *[]TypeInfo) error
	IsReady(req PluginRequest, res *IsReadyResponse) error
	Name(req PluginRequest, res *string) error
	NameFrom(req PluginRequest, res *string) error
	Update(req PluginRequest, res *UpdateResponse) error
	GetConfig(req PluginRequest, res *framework.DependentResourceConfig) error
}
----

In typical RPC fashion, at least when it comes to Go's implementation, the server exposes a set of functions which all follow
the `<function name>(<input parameter>, <pointer to a response holder>) error` format, which is less than natural to interact
with. This why we make sure that plugin implementors don't need to deal with this and we only show this interface for reference
purposes, rejoice! :smile:

=== Plugin implementation

While the RPC part of the infrastructure is abstracted away but the Halkyon plugins architecture, plugin implementors still
need to write some code in order to implement the capabilities they want to support. This behavior is encapsulated in one single
interface:

[source,go]
----
// PluginResource gathers behavior that plugin implementors are expected to provide to the plugins architecture
type PluginResource interface {
	// GetSupportedCategory returns the CapabilityCategory that this plugin supports
	GetSupportedCategory() halkyon.CapabilityCategory
	// GetSupportedTypes returns the list of supported CapabilityTypes along with associated versions when they exist.
	// Note that, while a plugin can only support one CapabilityCategory (e.g. "database"), a plugin can provide support for
	// multiple CapabilityTypes (e.g. "postgresql", "mysql", etc.) within the confine of the specified category.
	GetSupportedTypes() []TypeInfo
	// GetDependentResourcesWith returns an ordered list of DependentResources initialized with the specified owner.
	// DependentResources represent secondary resources that the capability might need to work (e.g. Kubernetes Role or Secret)
	// along with the resource (if it exists) implementing the capability itself (e.g. KubeDB's Postgres).
	GetDependentResourcesWith(owner v1beta1.HalkyonResource) []framework.DependentResource
}
----

As you can see this closely mirrors the `Plugin` interface that the operator can interact with but is strictly focused on
providing the required behavior with as simple an interface as possible.

In order to implement a plugin, you will need to create a go project importing this project and create a main function similar
to the following one:

[source,go]
----
package main

import (
	plugins "halkyon.io/plugins/capability"
)

func main() {
	var p plugins.PluginResource = ... // create an instance of your PluginResource implementation
    plugins.StartPluginServerFor(p) // register your server and start it
}
----

You, of course, need to provide your own `PluginResource` implementation.

=== Example

A full-featured example can be seen at https://github.com/halkyonio/kubedb-capability

== Using plugins in Halkyon

Halkyon will attempt to load every file it finds in its local `plugins` directory as a plugin. These files need to be binaries
that can be run on the platform you're running the operator on. As a convenience, it is possible to pass a comma-separated list
of plugins to automatically download from github repositories to the operator. This is accomplished using the `HALKYON_PLUGINS`
environment variable (which can, of course, be provided via a ConfigMap). Each plugin in the list is identified by a string
following the `<github org>/<repository name>@<release name>`. When encountering such a plugin identifier, Halkyon will attempt
to download a file found at: `https://github.com/<github org>/releases/download/<repository name>/halkyon_plugin_<target OS>.tar.gz`
where `<target OS>` corresponds to the value reported by by the Go runtime under the `runtime.GOOS` value in the running operator.
A good way to make sure that your plugin is downloadable by Halkyon is to use https://goreleaser.com/[GoReleaser] combined with
GitHub actions. See https://github.com/halkyonio/kubedb-capability for more details.
